services:
  scheduler.api:
    image: ${DOCKER_REGISTRY-}schedulerapi
    container_name: scheduler.api
    build:
      context: .
      dockerfile: Scheduler.Api/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=schedulerdb;Username=scheduler;Password=schedulerpass
    networks:
      - dotnet

  postgres:
    image: postgres:16
    container_name: scheduler.postgres
    restart: always
    environment:
      POSTGRES_DB: schedulerdb
      POSTGRES_USER: scheduler
      POSTGRES_PASSWORD: schedulerpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - dotnet
    

volumes:
  pgdata:
      driver: local

networks:
    dotnet:
        driver: bridge