version: '3.8'

services:
  postgres_db:
    image: postgres:15
    container_name: scheduler_postgres_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=distrito@404
      - POSTGRES_DB=SchedulerDb
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  scheduler.api:
    image: ${DOCKER_REGISTRY-}schedulerapi
    container_name: scheduler.api
    build:
      context: .
      dockerfile: Scheduler.Api/Dockerfile
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=postgres_db;Port=5432;Database=SchedulerDb;User Id=postgres;Password=distrito@404;
    depends_on:
      - postgres_db

volumes:
  db_data: