@Scheduler.Api_HostAddress = http://localhost:5247

GET {{Scheduler.Api_HostAddress}}/swagger/
GET {{Scheduler.Api_HostAddress}}/v1/
GET {{Scheduler.Api_HostAddress}}/v1/secure/
Accept: application/json

###
